### ISSUE TITLE
Some animation or sound between levels...

### ISSUE THREAD

**Issue by SamLaco** [enuminatti-project1/spacebadjoraz#23]
Make one method to be called when the player passes from one level to another

**Comment by wiiaboo** [comment]
https://github.com/enuminatti-project1/spacebadjoraz/pull/25

**Comment by wiiaboo** [comment]
Bullets hit sound gets cut off if multiple bullets hit at once @SamLaco

**Comment by wiiaboo** [comment]
Done.
