### ISSUE TITLE
PlayerShip stops shooting when it starts moving

### ISSUE THREAD

**Issue by FXalana** [enuminatti-project1/spacebadjoraz#5]
Maybe check with the MCs on what's the reason?

**Comment by wiiaboo** [comment]
But shooting works if you start shooting while moving, as long as you don't change directions.

**Comment by wiiaboo** [comment]
Fixed in https://github.com/enuminatti-project1/spacebadjoraz/commit/6095e609e39f8c50eb2c772cec6212ec638f5c74 and 0ee22d2.
